// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl73Gjxt9L5WP9o056-vD9bETANPFWnvo',
    appId: '1:761735389071:web:6f23bd59caab58dfbb75fa',
    messagingSenderId: '761735389071',
    projectId: 'therapy-app-7918c',
    authDomain: 'therapy-app-7918c.firebaseapp.com',
    storageBucket: 'therapy-app-7918c.appspot.com',
    measurementId: 'G-5Z4BWPYGGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5cUq_MHzb_9JvLrpynrcxLy-KIC-EOYk',
    appId: '1:761735389071:android:2141e5cfe34727fcbb75fa',
    messagingSenderId: '761735389071',
    projectId: 'therapy-app-7918c',
    storageBucket: 'therapy-app-7918c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6fmyL6XfA4-yotPeTuODhaig6l9N0PTQ',
    appId: '1:761735389071:ios:2bba35619ab98c3ebb75fa',
    messagingSenderId: '761735389071',
    projectId: 'therapy-app-7918c',
    storageBucket: 'therapy-app-7918c.appspot.com',
    iosClientId: '761735389071-403h06pfssmn8ep1ttt4a1nfshavavh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.terapyApp',
  );
}
